### ISSUE TITLE
Week 6 Team Ticket: Project Approval

### ISSUE THREAD

**Issue by Rebecca-123** [Rebecca-123/blog_juiceVRLD#11]
**Scores**
| Name | Score |
|--------|--------|
| Linda Liu | 2.6/3 |
| Vaishavi Jayashankar | 2.4/3 |
| Divyanshi Suri | 2.6/3 |
| Rebecca Su | 3/3 |

[Team Project](https://rebecca-123.github.io/blog_juiceVRLD/pbl/2022/09/23/brainwrite.html)

**Individual/Pair**

- Arrays and Images
- Fetch/Backend RapidAPI

**Team**
- Value and Interest

**Comment by PranaviInukurti** [comment]
- nice job taking criticism into consideration
- good/unique idea for the website
- nice planning and organization for future possible APIs
- good job thoroughly explaining what each person will do and connecting it to team roles
- good overall understanding of their website plans and this week's work on ASCII and APIs using fetch

**Comment by mnarayan1** [comment]
- Narrowed down scope of project to CA, few APIs
- More focus on features than aesthetic
- Using POJO for user rating
- Included team roles
- Well organized presentation, everyone participated

**Comment by jm1021** [comment]
Travel Website.  Made three cities in CA for their emphasis.  Weather API.  POJO used for user, ratings of restaurants.   Calendar / Itinerary.    Start with localstorage.  Make a picture of deployment.  Wireframes are built.  Good team transitions on everything!!!! +++++

Devya -   Jupyter notebook and API page  2.6, no api
Linda - Grey, Red, Green.  2.6 , no api
Rebecca - Adapted display of last year with all the colors.  3.0
S - 2.4

**Comment by ftc13184-SK** [comment]
- Good use of last week's feedback to narrow their project iea
- Used POJO 
- each person had a good idea of what they would be doing in their project

**Comment by MAnn223** [comment]
- Travel Website 
- narrowed it down to a few cities in CA
- Weather API
- POJO - rate
- link to account 
- explained how each role would contribute to project - nice teamwork 
- wireframes
