### ISSUE TITLE
Week 4 Team Ticket

### ISSUE THREAD

**Issue by Rebecca-123** [Rebecca-123/blog_juiceVRLD#3]
**Scores**
| Name | Score |
|--------|--------|
| Linda Liu | 2.7/3 |
| Vaishavi Jayashankar | 2.6/3 |
| Divyanshi Suri | /3 |
| Rebecca Su | 3/3 |

**Agile Hacks**
[Team Scrum Board](https://github.com/users/Rebecca-123/projects/2)
[README](https://github.com/Rebecca-123/blog_juiceVRLD#readme)

**Pair FRQs**
1. [2019 FRQ](https://rebecca-123.github.io/fastpage-CSA/frq/mcs)
- Vaishavi
- Rebecca

**Individual Mini-Labs**
We have two separate mini-labs, one with apples and one with monkeys, but we worked together on vertical and horizontal implementations.
1. [Iteration Mini-Lab Part 1](https://lindaliu1202.github.io/lindaliu_blog/jupyter/2022/09/14/iteration_2dArray.html)
- Linda
2. [Iteration Mini-Lab Part 2](https://rebecca-123.github.io/fastpage-CSA/pbl/java/iteration)
- Rebecca

**Comment by PranaviInukurti** [comment]
- Very organized Team Scrum Board
- Have assigned team roles included and clearly stated
- Each pair showed good understanding and learning through explanation on each part of the FRQs
- Very good overall organization of learning throughout presentation
- I liked linda's apples
- good understanding of iterations

**Comment by MAnn223** [comment]
- Good team work: Team Scrumboard with roles
- Pair FRQs: 2019 - explained the question and solution, graded, covered key ideas
- Mini Labs: Linda: monekys to apples, printed horizontally, Rebecca: added monkeys/changed rows, horizontal monkeys, OOP monkeys, backend hacks (added character counter, fixed deployment problem)

**Comment by ftc13184-SK** [comment]
- Great team scrum board 
- 2019 FRQ Part A uses leap year method. Part B calculates additional days of a leap year
- Posted both the correct and incorrect solutions of the frq and key ideas to show learning 
-  Linda changed the monkeys to apples and displayed one apple at a time
- Did the array horizontally  
- Rebecca changed the monkey's horizontally by iterating through the row and updated her backend

**Comment by jm1021** [comment]
Rebecca - agile hacks: scrum board and roles.  Discussed doing part two right and wrong and talked about testing.  Gave background and learning using substring, equals, and lenght.  Made Monkeys a different size.  Real nice object overview.   Did backend work.  3.0
Vaishavi 2019 FRQ leap years discussed loop logic using +1 2.6
Linda 2D array mini lab.  Had static in code should use length (bug).  Version 1: Changed data in array.  Changed row and col, did use lenght in later method.  Lots of iterations. 2.7
Dev - nothing shown.

**Comment by lwu1822** [comment]
* Team scrumboard with roles created
* 2019 FRQ: Answered with corrections, also has a summary of learnings
* Iteration with 2D Array: Linda: Changed monkeys to apples, using three methods to print horizontally, and printing backwards
* Rebecca: Added more monkeys, printed horizontal monkeys, printed monkeys with one objects

**Comment by mnarayan1** [comment]
- Team scrum board is well organized
- Good job on FRQs, I especially liked how you included a summary for the key concepts you covered in the FRQ
- The apple iteration minilab was very creative!
- Overall, your presentation was well organized and easy to follow
