### ISSUE TITLE
Week 5 Review Ticket

### ISSUE THREAD

**Issue by Rebecca-123** [Rebecca-123/blog_juiceVRLD#5]
**Individual**

- Fibonacci
- JavaScript and HTML

**Team**
- [Design](https://rebecca-123.github.io/blog_juiceVRLD/pbl/2022/09/23/brainwrite.html)

**Task Specific Tickets**
1. [Wireframes](https://github.com/Rebecca-123/blog_juiceVRLD/issues/8)
2. [Backend](https://github.com/Rebecca-123/blog_juiceVRLD/issues/9)

**Comment by jm1021** [comment]
V - After-School org or Travel.   Had ideas and several bullets.
L - Figma designs.  Traveling 4 Life.  Travel Search and and Itenerary.  
D - Hotels and Reviews and Money Conversions.  
R - Large UML style diagram with database tables.  Discussed Login which is feature that is somewhat difficult.  Impressive on discussion and all the deep thinking.   Shared Fibo, suggest Nth constructor in sub class.  


Perhaps should discuss somethings you are mimicking as there are several ideas out there.   These are things with lots of data and screens.  This is a very big system.

Rebecca 2.8, others missing verification of work.

**Comment by CalissaT** [comment]
Grade: 2.7+/3

- After-school organization tool or travel website 
    - Lots of good features, thought of data usage (API), and good wireframe
    - Review page could use some work to fit the style of the other page
- Rebecca did a really good job on the Fibo Lab

**Comment by kiannp44** [comment]
Grade: 2.7+/3

- Travel website, showed how they will incorporate APIs and how they will build on their project. Gave detailed explanation and showed their passion on the project. 
- Good wireframe for project very detailed and thorough and simple. Gives examples of front end development and backend development. I also really like the graph given to show how things would work.

**Comment by deimie** [comment]
Grade: 2.7+/3

* Design
  * Includes data management plan
  * wireframes
* Fibonacci
  * Includes extend
* JS
  * Good job on functioning js to html
